In [432]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
from sklearn.ensemble import RandomForestClassifier

# Загрузка данных

In [433]:
df = pd.read_csv("student_depression_dataset.csv", index_col=0)
df

,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
id,,,,,,,,,,,,,,,,,
2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [434]:
Y = df['Depression']
df.drop(['Depression'],inplace=True,axis=1)
df.head()

,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,,
2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No
8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes
26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes
30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes
32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No

# Удаление лишних столбцов

In [435]:
df.drop(['City'],axis=1,inplace=True)
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,
2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No
8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes
26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes
30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes
32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No

# Обработка пропусков

In [436]:
df.isna().sum()

Gender                                   0
Age                                      0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
dtype: int64

In [437]:
Y.isna().sum()

np.int64(0)

# Перевод категориальных признаков в численные

In [438]:
for i in df.columns:
    print(i)
    print(df[i].unique())

Gender
['Male' 'Female']
Age
[33. 24. 31. 28. 25. 29. 30. 27. 19. 20. 23. 18. 21. 22. 34. 32. 26. 39.
 35. 42. 36. 58. 49. 38. 51. 44. 43. 46. 59. 54. 48. 56. 37. 41.]
Profession
['Student' "'Civil Engineer'" 'Architect' "'UX/UI Designer'"
 "'Digital Marketer'" "'Content Writer'" "'Educational Consultant'"
 'Teacher' 'Manager' 'Chef' 'Doctor' 'Lawyer' 'Entrepreneur' 'Pharmacist']
Academic Pressure
[5. 2. 3. 4. 1. 0.]
Work Pressure
[0. 5. 2.]
CGPA
[ 8.97    5.9     7.03    5.59    8.13    5.7     9.54    8.04    9.79
  8.38    6.1     7.04    8.52    5.64    8.58    6.51    7.25    7.83
  9.93    8.74    6.73    5.57    8.59    7.1     6.08    5.74    9.86
  6.7     6.21    5.87    6.37    9.72    5.88    9.56    6.99    5.24
  9.21    7.85    6.95    5.86    7.92    9.66    8.94    9.71    7.87
  5.6     7.9     5.46    6.79    8.7     7.38    8.5     7.09    9.82
  8.89    7.94    9.11    6.75    7.53    9.49    9.01    7.64    5.27
  6.      9.44    5.75    7.51    9.05    6.38    8.95    9.88    5.32
  6.27    7.7     8.1     9.59    8.96    5.51    7.43    8.79    9.95
  5.37    6.86    8.32    9.74    5.66    7.48    8.23    8.81    6.03
  5.56    5.68    5.14    7.61    6.17    8.17    9.87    8.75    6.16
  9.5     7.99    5.67    8.92    6.19    5.76    6.25    5.11    5.58
  5.65    9.89    8.03    6.61    9.41    8.64    7.21    8.28    6.04
  9.13    8.08    9.96    5.12    8.35    7.07    9.6     9.24    8.54
  8.78    8.93    8.91    9.04    6.83    5.85    7.74    6.41    8.9
  7.75    7.88    5.42    7.52    7.68    8.4     9.39    6.84    5.99
  8.62    8.53    7.47    6.78    6.42    9.92    8.39    5.89    7.22
  6.81    9.02    9.97    9.63    9.67    5.41    7.27    6.05    6.85
  9.33    5.81    6.53    5.98    6.02    6.74    5.26    7.72    7.39
  8.43    9.34    5.44    5.82    5.72    8.19    8.44    8.98    9.37
  5.8     7.28    7.6     7.91    9.17    7.46    9.43    9.91    9.36
  5.16    7.08    9.26    8.83   10.      7.8     9.46    6.63    7.24
  6.47    7.77    5.06    7.17    8.24    6.88    9.03    5.08    5.45
  8.46    9.19    6.36    8.73    7.11    9.12    9.4     8.11    9.98
  5.55    8.61    8.14    6.89    9.84    5.48    8.21    7.82    8.55
  5.79    8.77    8.29    6.92    7.37    9.7     6.26    7.26    7.5
  6.82    7.15    5.77    5.91    5.1     7.71    9.06    5.71    5.84
  9.42    6.23    6.29    5.25    9.69    9.9     6.39    8.09    5.83
  5.47    6.56    8.71    9.94    6.69    5.52    7.3     7.02    6.33
  8.07    8.37    8.      7.79    8.65    6.28    7.35    8.69    7.12
  7.32    7.13    5.97    5.09    6.91    6.76    6.52    7.45    8.56
  6.5     8.63    8.27    8.49    6.59    9.29    5.3     7.06    5.38
  6.65    9.16    8.01    8.25    8.02    8.47    7.34    8.88    7.14
  8.42    5.17    9.1     7.49    9.85    7.42    9.31    6.35    7.
  5.39    5.61    9.78    9.25    5.69    9.47    8.16    7.23    6.46
  0.      8.26    6.32    6.77    8.85    5.03    7.65    5.78    6.24
  5.35    6.06    7.78    6.64    7.0625  6.98    6.44    6.09  ]
Study Satisfaction
[2. 5. 3. 4. 1. 0.]
Job Satisfaction
[0. 3. 4. 2. 1.]
Sleep Duration
["'5-6 hours'" "'Less than 5 hours'" "'7-8 hours'" "'More than 8 hours'"
 'Others']
Dietary Habits
['Healthy' 'Moderate' 'Unhealthy' 'Others']
Degree
['B.Pharm' 'BSc' 'BA' 'BCA' 'M.Tech' 'PhD' "'Class 12'" 'B.Ed' 'LLB' 'BE'
 'M.Ed' 'MSc' 'BHM' 'M.Pharm' 'MCA' 'MA' 'B.Com' 'MD' 'MBA' 'MBBS' 'M.Com'
 'B.Arch' 'LLM' 'B.Tech' 'BBA' 'ME' 'MHM' 'Others']
Have you ever had suicidal thoughts ?
['Yes' 'No']
Work/Study Hours
[ 3.  9.  4.  1.  0. 12.  2. 11. 10.  6.  8.  5.  7.]
Financial Stress
['1.0' '2.0' '5.0' '3.0' '4.0' '?']
Family History of Mental Illness
['No' 'Yes']

## Label encode

In [439]:
def convert_sleep_duration_to_int(x):
    if x == "'Less than 5 hours'":
        return 1
    elif x == "'5-6 hours'":
        return 2
    elif x == "'7-8 hours'":
        return 3
    elif x == "'More than 8 hours'":
        return 4
    
    return np.nan

df["Sleep Duration"] = df["Sleep Duration"].apply(convert_sleep_duration_to_int).astype("Int64")
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,
2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,2,Healthy,B.Pharm,Yes,3.0,1.0,No
8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,2,Moderate,BSc,No,3.0,2.0,Yes
26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,1,Healthy,BA,No,9.0,1.0,Yes
30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,3,Moderate,BCA,Yes,4.0,5.0,Yes
32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,2,Moderate,M.Tech,Yes,1.0,1.0,No

In [440]:
def convert_dietary_habits_to_int(x):
    if x == 'Unhealthy':
        return 1
    elif x == 'Moderate':
        return 2
    elif x == 'Healthy':
        return 3
    
    return np.nan

df["Dietary Habits"] = df["Dietary Habits"].apply(convert_dietary_habits_to_int).astype("Int64")
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,
2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,2,3,B.Pharm,Yes,3.0,1.0,No
8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,2,2,BSc,No,3.0,2.0,Yes
26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,1,3,BA,No,9.0,1.0,Yes
30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,3,2,BCA,Yes,4.0,5.0,Yes
32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,2,2,M.Tech,Yes,1.0,1.0,No

In [441]:
df["Have you ever had suicidal thoughts ?"] = df["Have you ever had suicidal thoughts ?"].apply(lambda x: 1 if x == 'Yes' else 0).astype(int)
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,
2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,2,3,B.Pharm,1,3.0,1.0,No
8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,2,2,BSc,0,3.0,2.0,Yes
26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,1,3,BA,0,9.0,1.0,Yes
30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,3,2,BCA,1,4.0,5.0,Yes
32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,2,2,M.Tech,1,1.0,1.0,No

In [442]:
df["Family History of Mental Illness"] = df["Family History of Mental Illness"].apply(lambda x: 1 if x == 'Yes' else 0).astype(int)
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,
2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,2,3,B.Pharm,1,3.0,1.0,0
8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,2,2,BSc,0,3.0,2.0,1
26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,1,3,BA,0,9.0,1.0,1
30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,3,2,BCA,1,4.0,5.0,1
32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,2,2,M.Tech,1,1.0,1.0,0

## One hot encode

In [443]:
df = pd.get_dummies(df, columns=["Gender", "Profession", "Degree"], dtype=int, drop_first=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27901 entries, 2 to 140699
Data columns (total 53 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    27901 non-null  float64
 1   Academic Pressure                      27901 non-null  float64
 2   Work Pressure                          27901 non-null  float64
 3   CGPA                                   27901 non-null  float64
 4   Study Satisfaction                     27901 non-null  float64
 5   Job Satisfaction                       27901 non-null  float64
 6   Sleep Duration                         27883 non-null  Int64
 7   Dietary Habits                         27889 non-null  Int64
 8   Have you ever had suicidal thoughts ?  27901 non-null  int64
 9   Work/Study Hours                       27901 non-null  float64
 10  Financial Stress                       27901 non-null  object
 11  Family History of Mental Illness       27901 non-null  int64
 12  Gender_Male                            27901 non-null  int64
 13  Profession_'Content Writer'            27901 non-null  int64
 14  Profession_'Digital Marketer'          27901 non-null  int64
 15  Profession_'Educational Consultant'    27901 non-null  int64
 16  Profession_'UX/UI Designer'            27901 non-null  int64
 17  Profession_Architect                   27901 non-null  int64
 18  Profession_Chef                        27901 non-null  int64
 19  Profession_Doctor                      27901 non-null  int64
 20  Profession_Entrepreneur                27901 non-null  int64
 21  Profession_Lawyer                      27901 non-null  int64
 22  Profession_Manager                     27901 non-null  int64
 23  Profession_Pharmacist                  27901 non-null  int64
 24  Profession_Student                     27901 non-null  int64
 25  Profession_Teacher                     27901 non-null  int64
 26  Degree_B.Arch                          27901 non-null  int64
 27  Degree_B.Com                           27901 non-null  int64
 28  Degree_B.Ed                            27901 non-null  int64
 29  Degree_B.Pharm                         27901 non-null  int64
 30  Degree_B.Tech                          27901 non-null  int64
 31  Degree_BA                              27901 non-null  int64
 32  Degree_BBA                             27901 non-null  int64
 33  Degree_BCA                             27901 non-null  int64
 34  Degree_BE                              27901 non-null  int64
 35  Degree_BHM                             27901 non-null  int64
 36  Degree_BSc                             27901 non-null  int64
 37  Degree_LLB                             27901 non-null  int64
 38  Degree_LLM                             27901 non-null  int64
 39  Degree_M.Com                           27901 non-null  int64
 40  Degree_M.Ed                            27901 non-null  int64
 41  Degree_M.Pharm                         27901 non-null  int64
 42  Degree_M.Tech                          27901 non-null  int64
 43  Degree_MA                              27901 non-null  int64
 44  Degree_MBA                             27901 non-null  int64
 45  Degree_MBBS                            27901 non-null  int64
 46  Degree_MCA                             27901 non-null  int64
 47  Degree_MD                              27901 non-null  int64
 48  Degree_ME                              27901 non-null  int64
 49  Degree_MHM                             27901 non-null  int64
 50  Degree_MSc                             27901 non-null  int64
 51  Degree_Others                          27901 non-null  int64
 52  Degree_PhD                             27901 non-null  int64
dtypes: Int64(2), float64(7), int64(43), object(1)
memory usage: 11.5+ MB

## Обработка пропусков

In [444]:
df.isna().sum()

Age                                       0
Academic Pressure                         0
Work Pressure                             0
CGPA                                      0
Study Satisfaction                        0
Job Satisfaction                          0
Sleep Duration                           18
Dietary Habits                           12
Have you ever had suicidal thoughts ?     0
Work/Study Hours                          0
Financial Stress                          0
Family History of Mental Illness          0
Gender_Male                               0
Profession_'Content Writer'               0
Profession_'Digital Marketer'             0
Profession_'Educational Consultant'       0
Profession_'UX/UI Designer'               0
Profession_Architect                      0
Profession_Chef                           0
Profession_Doctor                         0
Profession_Entrepreneur                   0
Profession_Lawyer                         0
Profession_Manager                        0
Profession_Pharmacist                     0
Profession_Student                        0
Profession_Teacher                        0
Degree_B.Arch                             0
Degree_B.Com                              0
Degree_B.Ed                               0
Degree_B.Pharm                            0
Degree_B.Tech                             0
Degree_BA                                 0
Degree_BBA                                0
Degree_BCA                                0
Degree_BE                                 0
Degree_BHM                                0
Degree_BSc                                0
Degree_LLB                                0
Degree_LLM                                0
Degree_M.Com                              0
Degree_M.Ed                               0
Degree_M.Pharm                            0
Degree_M.Tech                             0
Degree_MA                                 0
Degree_MBA                                0
Degree_MBBS                               0
Degree_MCA                                0
Degree_MD                                 0
Degree_ME                                 0
Degree_MHM                                0
Degree_MSc                                0
Degree_Others                             0
Degree_PhD                                0
dtype: int64

In [445]:
df["Sleep Duration"] = df["Sleep Duration"].fillna(df["Sleep Duration"].median())
df["Dietary Habits"] = df["Dietary Habits"].fillna(df["Dietary Habits"].median())

df.isna().sum()

Age                                      0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Gender_Male                              0
Profession_'Content Writer'              0
Profession_'Digital Marketer'            0
Profession_'Educational Consultant'      0
Profession_'UX/UI Designer'              0
Profession_Architect                     0
Profession_Chef                          0
Profession_Doctor                        0
Profession_Entrepreneur                  0
Profession_Lawyer                        0
Profession_Manager                       0
Profession_Pharmacist                    0
Profession_Student                       0
Profession_Teacher                       0
Degree_B.Arch                            0
Degree_B.Com                             0
Degree_B.Ed                              0
Degree_B.Pharm                           0
Degree_B.Tech                            0
Degree_BA                                0
Degree_BBA                               0
Degree_BCA                               0
Degree_BE                                0
Degree_BHM                               0
Degree_BSc                               0
Degree_LLB                               0
Degree_LLM                               0
Degree_M.Com                             0
Degree_M.Ed                              0
Degree_M.Pharm                           0
Degree_M.Tech                            0
Degree_MA                                0
Degree_MBA                               0
Degree_MBBS                              0
Degree_MCA                               0
Degree_MD                                0
Degree_ME                                0
Degree_MHM                               0
Degree_MSc                               0
Degree_Others                            0
Degree_PhD                               0
dtype: int64

# Обработка числовых признаков

## Объединение схожих столбцов

In [446]:
df[df["Work Pressure"] != 0]

,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,...,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD
id,,,,,,,,,,,,,,,,,,,,,
21880,38.0,0.0,5.0,0.0,0.0,4.0,2,3,0,2.0,...,0,0,0,0,0,0,0,0,0,0
75007,21.0,0.0,2.0,0.0,0.0,1.0,3,2,1,3.0,...,0,0,0,0,0,0,0,0,0,0
129756,18.0,0.0,5.0,0.0,0.0,4.0,3,2,1,9.0,...,0,0,0,0,0,0,0,0,0,0

In [447]:
df["Pressure"] = df["Academic Pressure"] + df["Work Pressure"]
df.drop(["Academic Pressure", "Work Pressure"], inplace=True, axis=1)
df.head()

,Age,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,...,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD,Pressure
id,,,,,,,,,,,,,,,,,,,,,
2,33.0,8.97,2.0,0.0,2,3,1,3.0,1.0,0,...,0,0,0,0,0,0,0,0,0,5.0
8,24.0,5.90,5.0,0.0,2,2,0,3.0,2.0,1,...,0,0,0,0,0,0,0,0,0,2.0
26,31.0,7.03,5.0,0.0,1,3,0,9.0,1.0,1,...,0,0,0,0,0,0,0,0,0,3.0
30,28.0,5.59,2.0,0.0,3,2,1,4.0,5.0,1,...,0,0,0,0,0,0,0,0,0,3.0
32,25.0,8.13,3.0,0.0,2,2,1,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,4.0

In [448]:
df[df["Job Satisfaction"] != 0]

,Age,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,...,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD,Pressure
id,,,,,,,,,,,,,,,,,,,,,
1428,29.0,9.63,3.0,3.0,3,2,0,8.0,5.0,0,...,0,0,0,0,0,0,0,0,0,3.0
21880,38.0,0.00,0.0,4.0,2,3,0,2.0,3.0,0,...,0,0,0,0,0,0,0,0,0,5.0
70453,20.0,0.00,0.0,2.0,1,2,1,12.0,3.0,1,...,0,0,0,0,0,0,0,0,0,0.0
75007,21.0,0.00,0.0,1.0,3,2,1,3.0,3.0,1,...,0,0,0,0,0,0,0,0,0,2.0
105773,18.0,0.00,0.0,1.0,1,2,1,9.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0.0
116703,25.0,9.44,5.0,2.0,1,1,1,4.0,1.0,0,...,0,0,0,0,0,0,0,0,1,4.0
129756,18.0,0.00,0.0,4.0,3,2,1,9.0,4.0,0,...,0,0,0,0,0,0,0,0,0,5.0
134830,24.0,0.00,0.0,2.0,4,1,0,0.0,5.0,0,...,0,0,0,0,0,0,0,0,0,0.0

## Обработка выбросов

In [449]:
df["Financial Stress"] = df["Financial Stress"].apply(lambda x: np.nan if x == "?" else x).astype("Float64")
df.head()

,Age,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,...,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD,Pressure
id,,,,,,,,,,,,,,,,,,,,,
2,33.0,8.97,2.0,0.0,2,3,1,3.0,1.0,0,...,0,0,0,0,0,0,0,0,0,5.0
8,24.0,5.90,5.0,0.0,2,2,0,3.0,2.0,1,...,0,0,0,0,0,0,0,0,0,2.0
26,31.0,7.03,5.0,0.0,1,3,0,9.0,1.0,1,...,0,0,0,0,0,0,0,0,0,3.0
30,28.0,5.59,2.0,0.0,3,2,1,4.0,5.0,1,...,0,0,0,0,0,0,0,0,0,3.0
32,25.0,8.13,3.0,0.0,2,2,1,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,4.0

In [450]:
df.isna().sum()

Age                                      0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Gender_Male                              0
Profession_'Content Writer'              0
Profession_'Digital Marketer'            0
Profession_'Educational Consultant'      0
Profession_'UX/UI Designer'              0
Profession_Architect                     0
Profession_Chef                          0
Profession_Doctor                        0
Profession_Entrepreneur                  0
Profession_Lawyer                        0
Profession_Manager                       0
Profession_Pharmacist                    0
Profession_Student                       0
Profession_Teacher                       0
Degree_B.Arch                            0
Degree_B.Com                             0
Degree_B.Ed                              0
Degree_B.Pharm                           0
Degree_B.Tech                            0
Degree_BA                                0
Degree_BBA                               0
Degree_BCA                               0
Degree_BE                                0
Degree_BHM                               0
Degree_BSc                               0
Degree_LLB                               0
Degree_LLM                               0
Degree_M.Com                             0
Degree_M.Ed                              0
Degree_M.Pharm                           0
Degree_M.Tech                            0
Degree_MA                                0
Degree_MBA                               0
Degree_MBBS                              0
Degree_MCA                               0
Degree_MD                                0
Degree_ME                                0
Degree_MHM                               0
Degree_MSc                               0
Degree_Others                            0
Degree_PhD                               0
Pressure                                 0
dtype: int64

In [451]:
df["Financial Stress"] = df["Financial Stress"].fillna(df["Financial Stress"].median())
df.isna().sum()

Age                                      0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Gender_Male                              0
Profession_'Content Writer'              0
Profession_'Digital Marketer'            0
Profession_'Educational Consultant'      0
Profession_'UX/UI Designer'              0
Profession_Architect                     0
Profession_Chef                          0
Profession_Doctor                        0
Profession_Entrepreneur                  0
Profession_Lawyer                        0
Profession_Manager                       0
Profession_Pharmacist                    0
Profession_Student                       0
Profession_Teacher                       0
Degree_B.Arch                            0
Degree_B.Com                             0
Degree_B.Ed                              0
Degree_B.Pharm                           0
Degree_B.Tech                            0
Degree_BA                                0
Degree_BBA                               0
Degree_BCA                               0
Degree_BE                                0
Degree_BHM                               0
Degree_BSc                               0
Degree_LLB                               0
Degree_LLM                               0
Degree_M.Com                             0
Degree_M.Ed                              0
Degree_M.Pharm                           0
Degree_M.Tech                            0
Degree_MA                                0
Degree_MBA                               0
Degree_MBBS                              0
Degree_MCA                               0
Degree_MD                                0
Degree_ME                                0
Degree_MHM                               0
Degree_MSc                               0
Degree_Others                            0
Degree_PhD                               0
Pressure                                 0
dtype: int64

# Нормализация

In [452]:
df_norm = (df - df.min()) / (df.max() - df.min())
df_norm

,Age,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,...,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD,Pressure
id,,,,,,,,,,,,,,,,,,,,,
2,0.365854,0.897,0.4,0.0,0.333333,1.0,1.0,0.250000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,0.146341,0.590,1.0,0.0,0.333333,0.5,0.0,0.250000,0.25,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4
26,0.317073,0.703,1.0,0.0,0.0,1.0,0.0,0.750000,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6
30,0.243902,0.559,0.4,0.0,0.666667,0.5,1.0,0.333333,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6
32,0.170732,0.813,0.6,0.0,0.333333,0.5,1.0,0.083333,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,0.219512,0.575,1.0,0.0,0.333333,0.0,1.0,0.583333,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140686,0.219512,0.940,0.6,0.0,0.0,1.0,0.0,0.000000,0.5,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.4
140689,0.317073,0.661,0.8,0.0,0.333333,0.0,0.0,1.000000,0.25,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.6
140690,0.000000,0.688,0.4,0.0,0.0,1.0,1.0,0.833333,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140699,0.219512,0.924,0.2,0.0,0.0,1.0,1.0,0.166667,0.5,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8

# Обучение модели

In [453]:
X_train, X_test, Y_train, Y_test = train_test_split(df_norm, Y, test_size=0.2, random_state=42, stratify=Y)

In [454]:
model = RandomForestClassifier(max_depth=10, random_state=42)
model.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [455]:
Y_pred = model.predict(X_test)

In [456]:
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

precision = precision_score(Y_test, Y_pred)
print("Precision:", precision)

Accuracy: 0.8369467837305142
Precision: 0.8423344947735192